[package]
name = "macros"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false
proc-macro = true

[dependencies]
darling.workspace = true
proc-macro-crate.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
